# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0002_auto_20160929_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
