# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0008_auto_20161026_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='posts'),
        ),
    ]
